export const games = [
  {
    name: 'katsaii_witchcraft',
    config: {
      config_version: 1,
      game_name: 'Witchcraft',
      authors: {
        katsaii: 'Katsaii',
        mashmerlow: 'Mashmerlow',
      },
      prompt: 'CRAFT',
      init_room: 'katsaii_witchcraft_rm',
      view_width: 1,
      view_height: 1,
      time_seconds: 7,
      music_track: 'katsaii_witchcraft_mu',
      music_loops: false,
      interpolation_on: true,
      cartridge_col_primary: [198, 119, 95],
      cartridge_col_secondary: [238, 199, 138],
      cartridge_label: 'katsaii_witchcraft_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['Katsaii', 'Mashmerlow'],
      date_added: {
        day: 9,
        month: 'July',
        year: 2021,
      },
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
      description: [
        "Okay, so basically you're a witch and you craft wands. Thats why the game is called Witchcraft. Okay submit that. No. Stop writing down what I'm saying. Just use the first bit. -- SPEECH-TO-TEXT --",
      ],
      how_to_play: [
        'Use the primary keys to select the highlighted items in order. Missing an item results in a game-over, so be careful. The arrow keys can be used to change the direction of the hand in order to save some time.',
      ],
    },
    authorIds: ['katsaii', 'mashmerlow'],
  },
  {
    name: 'katsaii_witchwanda',
    config: {
      config_version: 1,
      game_name: 'Witch Wanda',
      authors: {
        katsaii: 'Katsaii',
        mashmerlow: 'Mashmerlow',
      },
      prompt: 'SHOOT',
      init_room: 'katsaii_witchwanda_rm_game',
      view_width: -1,
      view_height: -1,
      time_seconds: 12,
      music_track: 'noone',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [204, 107, 102],
      cartridge_col_secondary: [232, 182, 181],
      cartridge_label: 'katsaii_witchwanda_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['Katsaii', 'Mashmerlow'],
      date_added: {
        day: 25,
        month: 'August',
        year: 2021,
      },
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
      description: [
        'You play as Wanda, a friendly witch flying through the sky amongst clouds and floating islands. Suddenly, a group of witches start to attack Wanda and her island. Defeat the wave of witches and protect the island!',
      ],
      how_to_play: [
        'Use the primary keys to file bullets at opposing witches. Holding down continuous fire will decrease the rate of fire over time, so try to fire in bursts. Use the arrow keys to move around and avoid the projectiles.',
      ],
    },
    authorIds: ['katsaii', 'mashmerlow'],
  },
  {
    name: 'makoren_conjurer',
    config: {
      config_version: 1,
      game_name: 'Conjurer',
      authors: 'Makoren',
      prompt: 'MATCH',
      init_room: 'makoren_conjurer_rm_main',
      view_width: 120,
      view_height: 80,
      time_seconds: 6,
      music_track: 'sng_ennway_bit_battle',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [153, 102, 255],
      cartridge_col_secondary: [69, 41, 95],
      cartridge_label: 'makoren_conjurer_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['Makoren'],
      date_added: '21/07/10',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['makoren'],
  },
  {
    name: 'kilomatter_jaywalker',
    config: {
      config_version: 1,
      game_name: 'Jay Walker',
      authors: 'Kilomatter',
      prompt: 'CROSS',
      init_room: 'kilo_jaywalker_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 6,
      music_track: 'sng_zandy_doctor',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [164, 70, 89],
      cartridge_col_secondary: [123, 23, 62],
      cartridge_label: 'kilo_jaywalker_sprCartLabel',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['Kilomatter', 'Zandy'],
      date_added: '21/08/17',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['kilomatter'],
  },
  {
    name: 'space_rocket_lander',
    config: {
      config_version: 1,
      game_name: 'Rocket Lander',
      authors: 'Space',
      prompt: 'LAND',
      init_room: 'space_lander_rm_lander',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'space_lander_sng_zandy_aliens_edit',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [0, 214, 179],
      cartridge_col_secondary: [0, 125, 150],
      cartridge_label: 'space_lander_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['space'],
      date_added: '21/07/04',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['space'],
  },
  {
    name: 'space_scooter',
    config: {
      config_version: 1,
      game_name: 'Rixel Rider',
      authors: 'Space',
      prompt: 'Backflip',
      init_room: 'space_scoot_rm',
      view_width: 120,
      view_height: 80,
      time_seconds: 6,
      music_track: 'space_scooter_sng_meseta_midnight_drive',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [180, 92, 117],
      cartridge_col_secondary: [43, 36, 56],
      cartridge_label: 'space_scooter_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['space', 'meseta', 'freesound.org', 'zapsplat.com'],
      date_added: '21/07/12',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['space'],
  },
  {
    name: 'yosi_epic_fire_truck',
    config: {
      config_version: 1,
      game_name: 'Epic Fire Truck',
      authors: 'Yosi',
      prompt: 'MASH',
      init_room: 'yosi_EFT_rm_init',
      view_width: 240,
      view_height: 160,
      time_seconds: 10,
      music_track: 'yosi_EFT_song',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [255, 50, 50],
      cartridge_col_secondary: [50, 50, 255],
      cartridge_label: 'yosi_EFT_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['yosi'],
      date_added: '21/07/08',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['yosi'],
  },
  {
    name: 'n8fl_escape1',
    config: {
      config_version: 1,
      game_name: 'Action Escape Pt 1',
      authors: {
        n8fl: 'net8floz',
      },
      prompt: 'Jump On The Car',
      init_room: 'n8fl_escape1_rm',
      view_width: 120,
      view_height: 80,
      time_seconds: 5,
      music_track: 'n8fl_escape1_music',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [89, 62, 71],
      cartridge_col_secondary: [122, 88, 89],
      cartridge_label: 'n8fl_escape1_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['net8floz', 'meseta', 'space', 'mixkit.c'],
      date_added: '21/07/07',
      is_enabled: false,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['n8fl'],
  },
  {
    name: 'n8fl_escape2',
    config: {
      config_version: 1,
      game_name: 'Action Escape Pt 2',
      authors: {
        n8fl: 'net8floz',
      },
      prompt: 'Jump On The Train',
      init_room: 'n8fl_escape2_rm',
      view_width: 120,
      view_height: 80,
      time_seconds: 5,
      music_track: 'n8fl_escape1_music',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [89, 62, 71],
      cartridge_col_secondary: [122, 88, 89],
      cartridge_label: 'n8fl_escape2_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['net8floz', 'meseta', 'space', 'mixkit.c'],
      date_added: '21/07/07',
      is_enabled: false,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['n8fl'],
  },
  {
    name: 'n8fl_penguin_blast',
    config: {
      config_version: 1,
      game_version: 1,
      game_version_date: {
        day: 21,
        month: 'July',
        year: 2021,
      },
      date_added: '21/07/05',
      game_name: 'Penguin Blast',
      authors: {
        n8fl: 'net8floz',
      },
      prompt: "Don't Get Blasted",
      init_room: 'n8fl_penguin_blast_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 10,
      music_track: 'sng_zandy_woodblocks',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [98, 98, 118],
      cartridge_col_secondary: [28, 22, 51],
      cartridge_label: 'n8fl_penguin_blast_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['net8floz'],
      is_enabled: false,
      description: [
        "The evil orange cat with sunglasses has kidnapped the fair Mimpy Penguin. The only problem? This penguin can't swim.",
      ],
      how_to_play: [
        'Use the Primary Key & Secondary key to match the Red and Green projectiles. Use the Down key to block bombs. Match all the projectiles and save the princess.',
      ],
      author_id: 'n8fl',
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['n8fl'],
  },
  {
    name: 'n8fl_reach_for_it_mister',
    config: {
      config_version: 1,
      game_version: 1,
      game_version_date: {
        day: 21,
        month: 'July',
        year: 2021,
      },
      date_added: '21/07/05',
      game_name: 'Reach For It, Mister',
      authors: {
        n8fl: 'net8floz',
      },
      description: [
        'The rad crew are at it again. But this time with cowboy hats.',
      ],
      how_to_play: [
        'Match the buttons on screen before your opponent does! Last hat standing.',
      ],
      prompt: 'Wait for it',
      init_room: 'n8fl_reach_for_it_mister_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 8,
      music_track: false,
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [89, 62, 71],
      cartridge_col_secondary: [122, 88, 89],
      cartridge_label: 'n8fl_reach_for_it_mister_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['nt8floz - game', 'meseta - music', 'space - art'],
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['n8fl'],
  },
  {
    name: 'mimpy_dinner_date',
    config: {
      config_version: 1,
      game_name: 'Dinner Date',
      authors: 'Mimpy',
      prompt: 'REST',
      init_room: 'mimpy_duckdate_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'mimpy_duckdate_mus_hop',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [76, 33, 33],
      cartridge_col_secondary: [102, 48, 48],
      cartridge_label: 'mimpy_duckdate_label',
      default_is_fail: false,
      supports_difficulty_scaling: false,
      credits: ['Mimpy'],
      date_added: '21/07/09',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['mimpy'],
  },
  {
    name: 'mimpy_fire_alarm',
    config: {
      config_version: 1,
      game_name: 'Fire Alarm',
      authors: 'Mimpy',
      prompt: 'DOUSE',
      init_room: 'mimpy_firealarm_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'mimpy_firealarm_emergency',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [200, 64, 28],
      cartridge_col_secondary: [102, 30, 32],
      cartridge_label: 'mimpy_firealarm_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['Mimpy'],
      date_added: '21/07/06',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['mimpy'],
  },
  {
    name: 'mimpy_objection',
    config: {
      config_version: 1,
      game_name: 'Objection!',
      authors: 'Mimpy',
      prompt: 'CONTRADICT',
      init_room: 'mimpy_objection_rm',
      view_width: 720,
      view_height: 480,
      time_seconds: 8,
      music_track: 'sng_ennway_bit_battle',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [94, 116, 204],
      cartridge_col_secondary: [177, 209, 215],
      cartridge_label: 'mimpy_objection_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['Mimpy'],
      date_added: '21/08/22',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['mimpy'],
  },
  {
    name: 'baku_chug',
    config: {
      config_version: 1,
      game_name: 'Forced Choice of a New Generation',
      authors: 'baku',
      prompt: 'CHUG',
      init_room: 'baku_chug_rm',
      view_width: 160,
      view_height: 107,
      time_seconds: 7,
      music_track: 'sng_zandy_xylo',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [148, 44, 75],
      cartridge_col_secondary: [98, 23, 72],
      cartridge_label: 'baku_chug_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['baku'],
      date_added: '21/07/08',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['baku'],
  },
  {
    name: 'baku_mine',
    config: {
      config_version: 1,
      game_name: 'Lonesome Miner',
      authors: 'baku',
      prompt: [
        'MINE DIAMOND',
        'MINE EMERALD',
        'MINE GOLD',
        'MINE RUBY',
        'MINE IRON',
      ],
      init_room: 'baku_mine_rm',
      view_width: 480,
      view_height: 320,
      time_seconds: 12,
      music_track: 'baku_mine_bgm_minecraft',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [96, 81, 88],
      cartridge_col_secondary: [42, 35, 37],
      cartridge_label: 'baku_mine_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['baku', 'meseta'],
      date_added: '21/07/21',
      is_enabled: true,
      supports_html: false,
      show_on_website: true,
    },
    authorIds: ['baku'],
  },
  {
    name: 'anti_hats',
    config: {
      config_version: 1,
      game_name: 'Hats',
      authors: 'Antidissmist',
      prompt: 'SHADES',
      init_room: 'anti_hats_rm_start',
      view_width: 240,
      view_height: 160,
      time_seconds: 4,
      music_track: 'anti_hats_music',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [29, 43, 83],
      cartridge_col_secondary: [126, 37, 83],
      cartridge_label: 'anti_hats_sp_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['Antidissmist'],
      date_added: '21/07/14',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['anti'],
  },
  {
    name: 'tfg_collision',
    config: {
      config_version: 1,
      game_name: 'FIX COLLISION',
      authors: 'tfg',
      prompt: 'FIND ERROR',
      init_room: 'tfg_collision_rm_game',
      view_width: 960,
      view_height: 640,
      time_seconds: 9.5,
      music_track: 'sng_ennway_bit_battle',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: '0x121212',
      cartridge_col_secondary: '0xffb871',
      cartridge_label: 'tfg_collision_spr_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['tfg', 'ennway', 'zandy'],
      date_added: '21/07/09',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['tfg'],
  },
  {
    name: 'tfg_swipe',
    config: {
      config_version: 1,
      game_name: 'SWIPE',
      authors: 'tfg',
      prompt: 'SWIPE',
      init_room: 'tfg_swipe_rm_game',
      view_width: -1,
      view_height: -1,
      time_seconds: 5,
      music_track: 'tfg_swipe_bgm_amogus',
      music_loops: false,
      interpolation_on: true,
      cartridge_col_primary: '0x555555',
      cartridge_col_secondary: '0x959595',
      cartridge_label: 'tfg_swipe_spr_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['tfg', 'zandy', 'space'],
      date_added: '21/08/15',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['tfg'],
  },
  {
    name: 'nahoo_beenade',
    config: {
      config_version: 1,
      game_name: 'Beenade',
      authors: 'Nahoo',
      prompt: 'POLLINATE',
      init_room: 'nahoo_beenade_rMain',
      view_width: 480,
      view_height: 320,
      time_seconds: 5,
      music_track: 'Nahoo_mMain',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [255, 244, 101],
      cartridge_col_secondary: [241, 161, 96],
      cartridge_label: 'Nahoo_beenade_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['Nahoo'],
      date_added: '21/07/04',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['nahoo'],
  },
  {
    name: 'nahoo_carttypebeat',
    config: {
      config_version: 1,
      game_name: 'Cart Type Beat',
      authors: 'Nahoo',
      prompt: 'REVOLT',
      init_room: 'nahoo_carttypebeat_rMain',
      view_width: 480,
      view_height: 320,
      time_seconds: 10,
      music_track: 'Nahoo_mMain',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [75, 38, 128],
      cartridge_col_secondary: [197, 59, 157],
      cartridge_label: 'Nahoo_carttypebeat_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: ['Nahoo'],
      date_added: '21/07/12',
      is_enabled: false,
      supports_html: false,
      show_on_website: true,
    },
    authorIds: ['nahoo'],
  },
  {
    name: 'jdllama_hammer',
    config: {
      config_version: 1,
      game_name: "THROWIN' THE HAMMER",
      authors: 'J.D. Lowe',
      prompt: 'THROW HAMMER',
      init_room: 'jdllama_hammer_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'noone',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [0, 0, 0],
      cartridge_col_secondary: [131, 147, 202],
      cartridge_label: 'jdllama_hammer_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['J.D. Lowe'],
      date_added: '21/08/12',
      is_enabled: false,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['jdllama'],
  },
  {
    name: 'jdllama_target',
    config: {
      config_version: 1,
      game_name: 'TARGET BREAKING YEAH',
      authors: 'J.D. Lowe',
      prompt: 'SHOOT THE TARGETS',
      init_room: 'jdllama_target_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'jdllama_target_snd_theme',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [0, 0, 0],
      cartridge_col_secondary: [55, 255, 255],
      cartridge_label: 'jdllama_target_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: ['J.D. Lowe', 'Zandy'],
      date_added: '21/08/09',
      is_enabled: true,
      supports_html: true,
      show_on_website: true,
    },
    authorIds: ['jdllama'],
  },
];
export const numGames = 23;
export const numContributors = 23;
